<a href="https://colab.research.google.com/github/arturoR13/arturoR13/blob/main/router%20status%20exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# network automation practice

# exercise 1: router status monitoring for loop.

In [10]:
routers=["192.168.1.1","192.186.1.2","192.186.1.3","192.186.1.4"]
for router in routers:
      if router.endswith(".3"):
          status = "offline"
      else:
            status = "online"
      print(router,status)

192.168.1.1 online
192.186.1.2 online
192.186.1.3 offline
192.186.1.4 online

# exercise 2: dynamic router list while loop

In [18]:
routers = []
while True:
      ip = input("enter router ip(or 'done' to finish):")
      if ip.lower()=="done":
            break
      routers.append(ip)
print("\nrouters registered:")

for router in routers:
      print(router)

enter router ip(or 'done' to finish):192.186.1.3
enter router ip(or 'done' to finish):192.186.1.6
enter router ip(or 'done' to finish):192.186.1.0
enter router ip(or 'done' to finish):192.186.1.5
enter router ip(or 'done' to finish):192.186.1.8
enter router ip(or 'done' to finish):done

routers registered:
192.186.1.3
192.186.1.6
192.186.1.0
192.186.1.5
192.186.1.8

# exercise 3 : router status monitoring_using dicctionaries

In [28]:
router_status = {}
while True:
      ip = input ("enter router ip or 'done' to finish:")
      if ip.lower() == "done":
              break
      router_status[ip]="online"
for ip, status in router_status.items():
  print(f"ip: {ip} - status: {status}")

enter router ip or 'done' to finish:192.186.1.5
enter router ip or 'done' to finish:192.186.1.9
enter router ip or 'done' to finish:done
ip: 192.186.1.5 - status: online
ip: 192.186.1.9 - status: online

# exercise 4: router search from csv file

In [60]:
with open("routers.csv","w")as f:
  f.write("name,ip,status\n")
  f.write("router_1,192.168.1.10,online\n")
  f.write("router_2,192.168.1.34,offline\n")
  f.write("router_3,192.168.1.4,online\n")
  f.write("router_4,192.168.1.2,online\n")

In [64]:
df.head()

       name            ip   status
0  router_1  192.168.1.10   online
1  router_2  192.168.1.34  offline
2  router_3   192.168.1.4   online
3  router_4   192.168.1.2   online

In [61]:
with open("routers.csv","r")as f:
  data = f.read()
  lines = data.strip().splitlines()
  headers = lines[0] .split(",")
  rows = lines[1:]
  print(f"{"name":<20} {"ip":<20} {"status":<15}")

name                 ip                   status

In [48]:
import pandas as pd

In [63]:
df = pd.read_csv("routers.csv")

In [52]:
df.head()

        name            ip  status
0  router_01  192.168.1.10  online

In [53]:
router_name = input("router name")

router namerouter_01

In [54]:
print(router_name)

router_01

In [57]:
resultado = df[df["name"] == router_name]

In [58]:
if resultado.empty:
  print("no se encontro el router")

In [59]:
resultado

        name            ip  status
0  router_01  192.168.1.10  online